import type { StackMode } from './types'

export const APP_MODE: StackMode = {
  id: 'app',
  name: 'App Stack',
  tagline: 'Click through each layer. Build your stack. Ship it.',
  layers: [
    {
      id: 'frontend', name: 'Frontend', subtitle: 'UI framework',
      items: [
        { id: 'nextjs', name: 'Next.js', domain: 'nextjs.org' },
        { id: 'react', name: 'React', domain: 'react.dev' },
        { id: 'vue', name: 'Vue', domain: 'vuejs.org' },
        { id: 'svelte', name: 'Svelte', domain: 'svelte.dev' },
        { id: 'astro', name: 'Astro', domain: 'astro.build' },
        { id: 'solidjs', name: 'SolidJS', domain: 'solidjs.com' },
        { id: 'angular', name: 'Angular', domain: 'angular.dev' },
        { id: 'remix', name: 'Remix', domain: 'remix.run' },
        { id: 'nuxt', name: 'Nuxt', domain: 'nuxt.com' },
      ],
    },
    {
      id: 'styling', name: 'Styling / UI', subtitle: 'Look & feel',
      items: [
        { id: 'tailwind', name: 'Tailwind CSS', domain: 'tailwindcss.com' },
        { id: 'shadcn', name: 'shadcn/ui', domain: 'ui.shadcn.com' },
        { id: 'radix', name: 'Radix UI', domain: 'radix-ui.com' },
        { id: 'chakra', name: 'Chakra UI', domain: 'chakra-ui.com' },
        { id: 'mantine', name: 'Mantine', domain: 'mantine.dev' },
        { id: 'mui', name: 'MUI', domain: 'mui.com' },
        { id: 'bootstrap', name: 'Bootstrap', domain: 'getbootstrap.com' },
      ],
    },
    {
      id: 'backend', name: 'Backend Runtime', subtitle: 'What runs your code',
      items: [
        { id: 'nodejs', name: 'Node.js', domain: 'nodejs.org' },
        { id: 'bun', name: 'Bun', domain: 'bun.sh' },
        { id: 'deno', name: 'Deno', domain: 'deno.com' },
        { id: 'python-fastapi', name: 'Python (FastAPI)', domain: 'fastapi.tiangolo.com' },
        { id: 'go', name: 'Go', domain: 'go.dev' },
        { id: 'rails', name: 'Ruby on Rails', domain: 'rubyonrails.org' },
        { id: 'phoenix', name: 'Elixir / Phoenix', domain: 'phoenixframework.org' },
        { id: 'nestjs', name: 'NestJS', domain: 'nestjs.com' },
        { id: 'hono', name: 'Hono', domain: 'hono.dev' },
        { id: 'dotnet', name: 'ASP.NET Core', domain: 'dotnet.microsoft.com' },
        { id: 'spring', name: 'Spring Boot', domain: 'spring.io' },
      ],
    },
    {
      id: 'hosting', name: 'Compute / Hosting', subtitle: 'Where it lives',
      items: [
        { id: 'vercel', name: 'Vercel', domain: 'vercel.com' },
        { id: 'cloudflare-workers', name: 'Cloudflare Workers', domain: 'cloudflare.com' },
        { id: 'aws-lambda', name: 'AWS Lambda', domain: 'aws.amazon.com' },
        { id: 'aws-ec2', name: 'AWS EC2', domain: 'aws.amazon.com' },
        { id: 'gcp-run', name: 'Google Cloud Run', domain: 'cloud.google.com' },
        { id: 'azure-app', name: 'Azure App Service', domain: 'azure.microsoft.com' },
        { id: 'fly', name: 'Fly.io', domain: 'fly.io' },
        { id: 'railway', name: 'Railway', domain: 'railway.app' },
        { id: 'render', name: 'Render', domain: 'render.com' },
        { id: 'netlify', name: 'Netlify', domain: 'netlify.com' },
        { id: 'digitalocean', name: 'DigitalOcean', domain: 'digitalocean.com' },
      ],
    },
    {
      id: 'database', name: 'Database', subtitle: 'Where data sleeps',
      items: [
        { id: 'postgres', name: 'PostgreSQL', domain: 'postgresql.org' },
        { id: 'neon', name: 'Neon', domain: 'neon.tech' },
        { id: 'supabase', name: 'Supabase', domain: 'supabase.com' },
        { id: 'planetscale', name: 'PlanetScale', domain: 'planetscale.com' },
        { id: 'mysql', name: 'MySQL', domain: 'mysql.com' },
        { id: 'mongodb', name: 'MongoDB', domain: 'mongodb.com' },
        { id: 'firebase', name: 'Firebase', domain: 'firebase.google.com' },
        { id: 'dynamodb', name: 'DynamoDB', domain: 'aws.amazon.com' },
        { id: 'convex', name: 'Convex', domain: 'convex.dev' },
        { id: 'turso', name: 'Turso', domain: 'turso.tech' },
        { id: 'd1', name: 'Cloudflare D1', domain: 'cloudflare.com' },
        { id: 'redis', name: 'Redis', domain: 'redis.io' },
      ],
    },
    {
      id: 'orm', name: 'ORM / Data Layer', subtitle: 'How you query',
      items: [
        { id: 'prisma', name: 'Prisma', domain: 'prisma.io' },
        { id: 'drizzle', name: 'Drizzle', domain: 'orm.drizzle.team' },
        { id: 'kysely', name: 'Kysely', domain: 'kysely.dev' },
        { id: 'typeorm', name: 'TypeORM', domain: 'typeorm.io' },
        { id: 'sequelize', name: 'Sequelize', domain: 'sequelize.org' },
        { id: 'raw-sql', name: 'Raw SQL', domain: 'postgresql.org' },
      ],
    },
    {
      id: 'auth', name: 'Auth', subtitle: "Who's logging in",
      items: [
        { id: 'clerk', name: 'Clerk', domain: 'clerk.com' },
        { id: 'auth0', name: 'Auth0', domain: 'auth0.com' },
        { id: 'supabase-auth', name: 'Supabase Auth', domain: 'supabase.com' },
        { id: 'authjs', name: 'Auth.js (NextAuth)', domain: 'authjs.dev' },
        { id: 'workos', name: 'WorkOS', domain: 'workos.com' },
        { id: 'firebase-auth', name: 'Firebase Auth', domain: 'firebase.google.com' },
        { id: 'better-auth', name: 'Better Auth', domain: 'better-auth.com' },
        { id: 'cognito', name: 'AWS Cognito', domain: 'aws.amazon.com' },
      ],
    },
    {
      id: 'storage', name: 'File / Blob Storage', subtitle: 'Big binary stuff',
      items: [
        { id: 's3', name: 'AWS S3', domain: 'aws.amazon.com' },
        { id: 'r2', name: 'Cloudflare R2', domain: 'cloudflare.com' },
        { id: 'vercel-blob', name: 'Vercel Blob', domain: 'vercel.com' },
        { id: 'gcs', name: 'Google Cloud Storage', domain: 'cloud.google.com' },
        { id: 'azure-blob', name: 'Azure Blob', domain: 'azure.microsoft.com' },
        { id: 'uploadthing', name: 'UploadThing', domain: 'uploadthing.com' },
      ],
    },
    {
      id: 'monitoring', name: 'Monitoring / APM', subtitle: 'Is it on fire?',
      items: [
        { id: 'sentry', name: 'Sentry', domain: 'sentry.io' },
        { id: 'datadog', name: 'Datadog', domain: 'datadoghq.com' },
        { id: 'newrelic', name: 'New Relic', domain: 'newrelic.com' },
        { id: 'grafana', name: 'Grafana', domain: 'grafana.com' },
        { id: 'honeycomb', name: 'Honeycomb', domain: 'honeycomb.io' },
        { id: 'axiom', name: 'Axiom', domain: 'axiom.co' },
        { id: 'better-stack', name: 'Better Stack', domain: 'betterstack.com' },
      ],
    },
    {
      id: 'product-analytics', name: 'Product Analytics', subtitle: 'What users actually do',
      items: [
        { id: 'posthog', name: 'PostHog', domain: 'posthog.com' },
        { id: 'amplitude', name: 'Amplitude', domain: 'amplitude.com' },
        { id: 'mixpanel', name: 'Mixpanel', domain: 'mixpanel.com' },
        { id: 'heap', name: 'Heap', domain: 'heap.io' },
        { id: 'june', name: 'June', domain: 'june.so' },
        { id: 'statsig', name: 'Statsig', domain: 'statsig.com' },
      ],
    },
    {
      id: 'web-analytics', name: 'Web Analytics', subtitle: 'Pageviews & vitals',
      items: [
        { id: 'ga', name: 'Google Analytics', domain: 'marketingplatform.google.com' },
        { id: 'plausible', name: 'Plausible', domain: 'plausible.io' },
        { id: 'fathom', name: 'Fathom', domain: 'usefathom.com' },
        { id: 'simple-analytics', name: 'Simple Analytics', domain: 'simpleanalytics.com' },
        { id: 'vercel-analytics', name: 'Vercel Analytics', domain: 'vercel.com' },
        { id: 'cf-analytics', name: 'Cloudflare Analytics', domain: 'cloudflare.com' },
      ],
    },
    {
      id: 'email', name: 'Transactional Email', subtitle: 'Reset links & receipts',
      items: [
        { id: 'resend', name: 'Resend', domain: 'resend.com' },
        { id: 'postmark', name: 'Postmark', domain: 'postmarkapp.com' },
        { id: 'sendgrid', name: 'SendGrid', domain: 'sendgrid.com' },
        { id: 'ses', name: 'AWS SES', domain: 'aws.amazon.com' },
        { id: 'mailgun', name: 'Mailgun', domain: 'mailgun.com' },
        { id: 'loops', name: 'Loops', domain: 'loops.so' },
      ],
    },
    {
      id: 'payments', name: 'Payments', subtitle: 'Take the money',
      items: [
        { id: 'stripe', name: 'Stripe', domain: 'stripe.com' },
        { id: 'lemonsqueezy', name: 'Lemon Squeezy', domain: 'lemonsqueezy.com' },
        { id: 'paddle', name: 'Paddle', domain: 'paddle.com' },
        { id: 'polar', name: 'Polar', domain: 'polar.sh' },
        { id: 'paypal', name: 'PayPal', domain: 'paypal.com' },
      ],
    },
    {
      id: 'ai', name: 'AI / LLM', subtitle: 'The smart bits',
      items: [
        { id: 'anthropic', name: 'Anthropic Claude', domain: 'anthropic.com' },
        { id: 'openai', name: 'OpenAI', domain: 'openai.com' },
        { id: 'gemini', name: 'Google Gemini', domain: 'ai.google.dev' },
        { id: 'vercel-ai', name: 'Vercel AI Gateway', domain: 'vercel.com' },
        { id: 'replicate', name: 'Replicate', domain: 'replicate.com' },
        { id: 'together', name: 'Together AI', domain: 'together.ai' },
        { id: 'groq', name: 'Groq', domain: 'groq.com' },
      ],
    },
    {
      id: 'search', name: 'Search', subtitle: 'Find stuff fast',
      items: [
        { id: 'algolia', name: 'Algolia', domain: 'algolia.com' },
        { id: 'meilisearch', name: 'Meilisearch', domain: 'meilisearch.com' },
        { id: 'typesense', name: 'Typesense', domain: 'typesense.org' },
        { id: 'elastic', name: 'Elastic', domain: 'elastic.co' },
        { id: 'postgres-fts', name: 'Postgres FTS', domain: 'postgresql.org' },
      ],
    },
    {
      id: 'cms', name: 'CMS / Content', subtitle: 'Marketing & blog',
      items: [
        { id: 'sanity', name: 'Sanity', domain: 'sanity.io' },
        { id: 'contentful', name: 'Contentful', domain: 'contentful.com' },
        { id: 'payload', name: 'Payload', domain: 'payloadcms.com' },
        { id: 'strapi', name: 'Strapi', domain: 'strapi.io' },
        { id: 'notion-cms', name: 'Notion', domain: 'notion.so' },
        { id: 'mdx', name: 'Markdown / MDX', domain: 'mdxjs.com' },
      ],
    },
    {
      id: 'cicd', name: 'CI / CD', subtitle: 'Ship it',
      items: [
        { id: 'gh-actions', name: 'GitHub Actions', domain: 'github.com' },
        { id: 'vercel-deploys', name: 'Vercel Deploys', domain: 'vercel.com' },
        { id: 'circleci', name: 'CircleCI', domain: 'circleci.com' },
        { id: 'gitlab-ci', name: 'GitLab CI', domain: 'gitlab.com' },
        { id: 'buildkite', name: 'Buildkite', domain: 'buildkite.com' },
      ],
    },
  ],
}

export const CONTENT_MODE: StackMode = {
  id: 'content',
  name: 'Content Stack',
  tagline: 'Pick your content style, then the tools you run your operation on.',
  layers: [
    {
      id: 'style', name: 'Content Style', subtitle: 'The flavor',
      kind: 'style',
      items: [
        { id: 'ugc', name: 'UGC' },
        { id: 'info', name: 'Info / Education' },
        { id: 'entertainment', name: 'Entertainment' },
        { id: 'edutainment', name: 'Edutainment' },
        { id: 'tutorial', name: 'Tutorial / How-to' },
        { id: 'review', name: 'Review / Reaction' },
        { id: 'vlog', name: 'Vlog' },
        { id: 'story', name: 'Storytelling / Docu' },
        { id: 'news', name: 'News / Commentary' },
      ],
    },
    {
      id: 'ideation', name: 'Ideation', subtitle: 'Where ideas start',
      items: [
        { id: 'notion', name: 'Notion', domain: 'notion.so' },
        { id: 'obsidian', name: 'Obsidian', domain: 'obsidian.md' },
        { id: 'airtable', name: 'Airtable', domain: 'airtable.com' },
        { id: 'chatgpt', name: 'ChatGPT', domain: 'openai.com' },
        { id: 'claude', name: 'Claude', domain: 'claude.ai' },
        { id: 'perplexity', name: 'Perplexity', domain: 'perplexity.ai' },
        { id: 'x-trends', name: 'X / Trends', domain: 'x.com' },
        { id: 'spyder', name: 'Trend scrapers' },
      ],
    },
    {
      id: 'scripting', name: 'Scripting / Writing', subtitle: 'Turning ideas into words',
      items: [
        { id: 'google-docs', name: 'Google Docs', domain: 'docs.google.com' },
        { id: 'notion-w', name: 'Notion', domain: 'notion.so' },
        { id: 'claude-w', name: 'Claude', domain: 'claude.ai' },
        { id: 'chatgpt-w', name: 'ChatGPT', domain: 'openai.com' },
        { id: 'hemingway', name: 'Hemingway', domain: 'hemingwayapp.com' },
        { id: 'grammarly', name: 'Grammarly', domain: 'grammarly.com' },
        { id: 'taja', name: 'Taja', domain: 'taja.ai' },
      ],
    },
    {
      id: 'voice', name: 'Voiceover', subtitle: 'Your voice, or an AI one',
      items: [
        { id: 'self', name: 'Your own voice' },
        { id: 'elevenlabs', name: 'ElevenLabs', domain: 'elevenlabs.io' },
        { id: 'play-ht', name: 'Play.ht', domain: 'play.ht' },
        { id: 'cartesia', name: 'Cartesia', domain: 'cartesia.ai' },
        { id: 'openai-voice', name: 'OpenAI TTS', domain: 'openai.com' },
        { id: 'descript-overdub', name: 'Descript Overdub', domain: 'descript.com' },
      ],
    },
    {
      id: 'editing', name: 'Video Editing', subtitle: 'Cutting it together',
      items: [
        { id: 'capcut', name: 'CapCut', domain: 'capcut.com' },
        { id: 'premiere', name: 'Premiere Pro', domain: 'adobe.com' },
        { id: 'final-cut', name: 'Final Cut Pro', domain: 'apple.com' },
        { id: 'davinci', name: 'DaVinci Resolve', domain: 'blackmagicdesign.com' },
        { id: 'descript', name: 'Descript', domain: 'descript.com' },
        { id: 'opus-clip', name: 'Opus Clip', domain: 'opus.pro' },
        { id: 'remotion', name: 'Remotion', domain: 'remotion.dev' },
      ],
    },
    {
      id: 'shortform', name: 'Short-form Platforms', subtitle: 'Quick hits',
      items: [
        { id: 'instagram-reels', name: 'Instagram Reels', domain: 'instagram.com' },
        { id: 'tiktok', name: 'TikTok', domain: 'tiktok.com' },
        { id: 'youtube-shorts', name: 'YouTube Shorts', domain: 'youtube.com' },
        { id: 'linkedin-short', name: 'LinkedIn (short)', domain: 'linkedin.com' },
        { id: 'x-video', name: 'X (video)', domain: 'x.com' },
      ],
    },
    {
      id: 'longform', name: 'Long-form Platforms', subtitle: 'Deep content',
      items: [
        { id: 'youtube', name: 'YouTube', domain: 'youtube.com' },
        { id: 'podcast', name: 'Podcast (Spotify/Apple)', domain: 'spotify.com' },
        { id: 'blog', name: 'Blog / Newsletter' },
        { id: 'linkedin-long', name: 'LinkedIn (long)', domain: 'linkedin.com' },
        { id: 'twitch', name: 'Twitch', domain: 'twitch.tv' },
      ],
    },
    {
      id: 'thumbnails', name: 'Thumbnails & Graphics', subtitle: 'Stop-the-scroll art',
      items: [
        { id: 'figma', name: 'Figma', domain: 'figma.com' },
        { id: 'canva', name: 'Canva', domain: 'canva.com' },
        { id: 'photoshop', name: 'Photoshop', domain: 'adobe.com' },
        { id: 'midjourney', name: 'Midjourney', domain: 'midjourney.com' },
        { id: 'nano-banana', name: 'Gemini (Nano Banana)', domain: 'gemini.google.com' },
        { id: 'ideogram', name: 'Ideogram', domain: 'ideogram.ai' },
      ],
    },
    {
      id: 'scheduling', name: 'Scheduling & Publishing', subtitle: 'Get it live',
      items: [
        { id: 'buffer', name: 'Buffer', domain: 'buffer.com' },
        { id: 'hootsuite', name: 'Hootsuite', domain: 'hootsuite.com' },
        { id: 'later', name: 'Later', domain: 'later.com' },
        { id: 'metricool', name: 'Metricool', domain: 'metricool.com' },
        { id: 'publer', name: 'Publer', domain: 'publer.com' },
        { id: 'native', name: 'Native schedulers' },
      ],
    },
    {
      id: 'analytics', name: 'Analytics', subtitle: 'Measure what works',
      items: [
        { id: 'native-insights', name: 'Native platform insights' },
        { id: 'tubebuddy', name: 'TubeBuddy', domain: 'tubebuddy.com' },
        { id: 'vidiq', name: 'vidIQ', domain: 'vidiq.com' },
        { id: 'metricool-a', name: 'Metricool', domain: 'metricool.com' },
        { id: 'shield-app', name: 'Shield (LinkedIn)', domain: 'shieldapp.ai' },
        { id: 'apify', name: 'Apify (custom scrapers)', domain: 'apify.com' },
      ],
    },
    {
      id: 'community', name: 'Community & Newsletter', subtitle: 'Own your audience',
      items: [
        { id: 'skool', name: 'Skool', domain: 'skool.com' },
        { id: 'circle', name: 'Circle', domain: 'circle.so' },
        { id: 'discord', name: 'Discord', domain: 'discord.com' },
        { id: 'beehiiv', name: 'Beehiiv', domain: 'beehiiv.com' },
        { id: 'substack', name: 'Substack', domain: 'substack.com' },
        { id: 'convertkit', name: 'ConvertKit / Kit', domain: 'kit.com' },
      ],
    },
    {
      id: 'monetization', name: 'Monetization', subtitle: 'Turn reach into revenue',
      items: [
        { id: 'adsense', name: 'YouTube AdSense', domain: 'adsense.google.com' },
        { id: 'sponsors', name: 'Brand sponsors' },
        { id: 'affiliates', name: 'Affiliates' },
        { id: 'digital-products', name: 'Digital products' },
        { id: 'courses', name: 'Courses / cohorts' },
        { id: 'coaching', name: '1:1 coaching' },
        { id: 'saas', name: 'SaaS / tool' },
      ],
    },
  ],
}

export const MODES: StackMode[] = [APP_MODE, CONTENT_MODE]

export function getMode(id: string): StackMode {
  return MODES.find(m => m.id === id) ?? APP_MODE
}
